import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='fixed top-0 left-0 right-0 h-20 flex justify-evenly items-center text-2xl border-b'>
          <Link href={'/'}> Karta</Link>
          <Link href={'/person'}>Kreator Kart</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
